name = "reader-books-router"
main = "reader-books-router.js"
compatibility_date = "2026-02-04"

routes = [
  { pattern = "reader.pub/books*", zone_name = "reader.pub" },
]

[[r2_buckets]]
binding = "BOOKS"
bucket_name = "reader-books"
